# Generated by Django 5.2 on 2025-05-02 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='complejo_administrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='administracion.complejohabitacional'),
        ),
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('LIMPIEZA', 'Limpieza'), ('SEGURIDAD', 'Seguridad'), ('ADMINISTRACION', 'Administración'), ('OTROS', 'Otros')], max_length=20)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_comunes', to='administracion.complejohabitacional')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Común',
                'verbose_name_plural': 'Gastos Comunes',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
